## Deliverable 3. Create a Travel Itinerary Map.

In [11]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [12]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
vacation_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Bredasdorp,ZA,2021-10-10 21:23:07,-34.5322,20.0403,61.29,87,70,3.44,broken clouds
1,1,Punta Arenas,CL,2021-10-10 21:20:22,-53.1500,-70.9167,51.91,37,20,31.07,few clouds
2,2,Busselton,AU,2021-10-10 21:23:18,-33.6500,115.3333,55.09,73,96,15.12,overcast clouds
3,3,Rikitea,PF,2021-10-10 21:18:17,-23.1203,-134.9692,74.62,80,97,19.73,overcast clouds
4,4,Williston,US,2021-10-10 21:21:04,48.1470,-103.6180,69.21,32,0,5.99,clear sky

In [13]:
clean_hotel_df = vacation_df.dropna()
clean_hotel_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Bredasdorp,ZA,2021-10-10 21:23:07,-34.5322,20.0403,61.29,87,70,3.44,broken clouds
1,1,Punta Arenas,CL,2021-10-10 21:20:22,-53.1500,-70.9167,51.91,37,20,31.07,few clouds
2,2,Busselton,AU,2021-10-10 21:23:18,-33.6500,115.3333,55.09,73,96,15.12,overcast clouds
3,3,Rikitea,PF,2021-10-10 21:18:17,-23.1203,-134.9692,74.62,80,97,19.73,overcast clouds
4,4,Williston,US,2021-10-10 21:21:04,48.1470,-103.6180,69.21,32,0,5.99,clear sky

In [14]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
<dt>Current Description</dt><dd>{Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [35]:
# 4a. Add a marker layer for each city to the map.
locations = clean_hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Savona")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Savona")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Rotterdam")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Lannion")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Plouzane")]

In [37]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = tuple(vacation_start[['Lat','Lng']].to_numpy()[0])
end = tuple(vacation_end[['Lat','Lng']].to_numpy()[0])
stop1 = tuple(vacation_stop1[['Lat','Lng']].to_numpy()[0])
stop2 = tuple(vacation_stop2[['Lat','Lng']].to_numpy()[0])
stop3 = tuple(vacation_stop3[['Lat','Lng']].to_numpy()[0])

In [39]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
# Latitude-longitude pairs

fig = gmaps.figure()
geneva2zurich = gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3], travel_mode='DRIVING')
fig.add_layer(geneva2zurich)
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,152,Savona,IT,2021-10-10 21:24:54,44.3000,8.2667,57.29,83,0,4.83,clear sky
1,511,Rotterdam,NL,2021-10-10 21:26:20,51.9225,4.4792,57.90,88,90,5.75,overcast clouds
2,576,Lannion,FR,2021-10-10 21:26:36,48.7500,-3.4167,60.67,94,75,4.61,broken clouds
3,208,Plouzane,FR,2021-10-10 21:25:09,48.3833,-4.6167,58.08,94,90,8.05,mist

In [41]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
<dt>Current Description</dt><dd>{Description}</dd>
</dl>
"""


# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [42]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))